# Generated by Django 4.0.3 on 2022-03-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorturl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.URLField()),
                ('original_url', models.URLField()),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
    ]
